### ISSUE TITLE
Ali Cloud `Show databases` command cannot be used with TARS installed by docker 

### ISSUE THREAD

**Issue by kasusa** [TarsCloud/Tars#513]
# Q

When using the Ali Cloud database, there will be an unauthorized problem, especially the command ` show Databases ` 

leads to docker's startup failure 

In ` High permission list`, there is no `show Databases` permission

![ss](http://ww1.sinaimg.cn/large/0083vuQJly1gdow3cp7mmj30pa08oabo.jpg)

I built it directly using docker.

**Comment by Douwanna** [comment]
_Here's the subsequence_
### Q:
When I creating the Cloud core and running it ,it report errors. 
![image](https://user-images.githubusercontent.com/33800612/79242730-432ecc00-7ea7-11ea-817f-f0fd5d05aa40.png)
This problem occurs when assigning permissions to `tarsAdmin`.

### A:
And then I deleted this permission in the tars-install script and tried again.In practice, it seems that show databases has not been used.

### Q:
where’s tars-install? I haven't even started docker. It reported errors when I was starting to build it.
![image](https://user-images.githubusercontent.com/33800612/79242813-5d68aa00-7ea7-11ea-876a-62f16de0d62e.png) 
There’s no data in these files.

### A:
Try this: [tarscloud/framework:dev](tarscloud/framework:dev) 
As I don't have Ali Cloud.,please tell me the result. If it runs well, I'll merge it into `stable` later.

### Q:
![image](https://user-images.githubusercontent.com/33800612/79243039-ade00780-7ea7-11ea-82e8-5b04509a5926.png)
It still errors.

### A:
Please try to use this sql to delete permissions **step by step** and find out which one can be passed.

### Q:
`CREATE TABLESPACE` This one can’t be passed.

### A：
Okay. Now you can update docker if you are free because I‘ve changed the SQL permissions.
The newly release is in the dev branch(from the same url). And then `pull `.
