### ISSUE TITLE
Can I deploy objects with different ports on a server?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#542]

**Comment by TARS-Answer** [comment]
E：An obj name corresponds to a port. For details, see < XXX. XXX. Obyadapter > in server.conf, where service, endpoint and protocol are one-to-one correspondence.
There won't be much benefit from deploying multiple instances on one server, because when the same service is deployed on one server, there will be no usability consideration. When one server hangs up, it will no longer provide available services.

C：一个obj name对应一个端口。具体可以看一下server.conf里的<xxx.xxx.objAdapter>，里面servant，endpoint和protocol是一一对应的；
一台服务器上面部署多个实例并不会有太多的收益 ，因为相同的服务部署在一台服务器上面 ，就没有可用性方面的考量了，当一台服务器挂掉的时候 ，就不再提供可用的服务了。
