### ISSUE TITLE
What is the aggregation idea of P90, p99 and p999? According to the algorithm, it should be assumed that cost is consistent with the uniform distribution, but in fact, cost is consistent with the long tail distribution. This data can't be calculated simply with the statistical value of two sets. How to deal with this?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#582]
![#582](https://user-images.githubusercontent.com/66677505/85204578-015b4f80-b348-11ea-92bd-927acccdd7d6.png)

**Comment by TARS-Answer** [comment]
Now P90 statistics is approximately average, which may not be strictly P90 data, because strictly P90 is to count the time-consuming of all requests, which will generate a lot of calculations. The current method is to calculate the P90 time-consuming of the request in the single pressure measurement process, and then weight the evaluation in the total process, which is approximate to the P90 data.            In addition, we need to consider the data escape in the data use case. When analyzing the use case, if there are commas in the actual data, there will be some problems in the separation. The earlier platform of TAF didn't solve this problem, so it's better to make JSON.            One solution is to modify these three keyword characters with \, convert them before cutting processing logic, and replace them when filling, and fix them here in the next version. Or use the parser combiner, boost:: Spirit x 3.

**Comment by TARS-Answer** [comment]
现在P90的统计是做了近似平均，可能不是严格意义的p90数据，因为严格意义的p90是要统计所有请求的耗时，这样会产生大量的计算。现在的做法是单压测进程计算周期内请求的P90耗时，然后在总进程里面加权评估，是近似P90数据。
除此之外，还需要考虑数据用例里的数据转义，解析用例的时候，万一实际数据也有逗号啥的，分隔会有点问题，之前这个taf早期那个平台也没有解决这个，还是得搞成json的最好。
一种解决方案是后面遇到这3个关键字符用\修饰一下，切割处理逻辑前转换一下，填充的时候再换回来，下个版本修复一下这里。或者用parser combinator，boost::spiritx3。
