### ISSUE TITLE
Test tars to support load balancing. 

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#587]
Try to run two applications, and observe whether there is an error when calling the two services through the registration center. Below is the test method. 

> ![#587(1)](https://user-images.githubusercontent.com/66677505/85220302-f6063380-b3dc-11ea-9c6e-ece917903887.png)

This test method always needs to restart the master node of docker, otherwise an error will be reported. When one service is stopped, another service will not be used.

> ![#587(2)](https://user-images.githubusercontent.com/66677505/85220305-fe5e6e80-b3dc-11ea-950a-7e55a04a3862.png)

**Comment by TARS-Answer** [comment]
A:
**Reason**: It is possible that the time of the database and the registry is not synchronized, resulting in that the newly added service does not load the endpoint information into memory. In theory, if you stop a service, the registry will not delete the information of the stopped servant endpoint. Unless the one-hour full load time expires, the client call will still return two endpoints, but the client will do a connectivity test and select the one with a smooth connection.

**Solution**: You can change the main frame time of tars to the time zone you want, such as +8 time zone, and then mysql modify the configuration file to +8 time zone. In addition, if the two applications are located on different physical machines, you need to make them between Keep time synchronized. You need to ensure that the time of the tars main control service is the same as the time of the virtual machine, otherwise the endpoint information cannot be loaded into memory.

**Comment by TARS-Answer** [comment]
**原因**：有可能数据库与registry的时间没有同步，导致新增加的服务没有将endpoint信息加载到内存中，理论上你停掉一个服务，registry是不会把停掉的servant的endpoint的信息删除的，除非等到一个小时的全量加载时间到了之后才会，客户端调用仍会返回两个endpoint，但客户端会做一个连接性测试，选出连接通畅的一个出来。
**解决方法**：你可以将tars的主框架时间改为你想要的时区，比如+8时区，然后mysql修改配置文件为+8时区，另外如果这两应用位于不同的物理机上，需要使他们之间保持时间同步。需要保证tars 主控服务的时间与虚拟机的时间是一样，否则endpoint信息没法加载到内存。
