### ISSUE TITLE
If the microservices are directly shut down and started via the Linux console, will the control of the web management background in the framework become invalid?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#591]
After manually starting and stopping the service, upload the publishing service again, why can't the service start? Operation process: stop is to kill the process directly in the linux console, start is to use the corresponding executable program of the microservice + corresponding configuration to start, that is, directly enter the executable program execution under the node, prompting that the exception is a port conflict.

**Comment by TARS-Answer** [comment]
Generally, it is not recommended to start and stop the service directly by logging in to the server. There are certain security issues. Start or stop the service directly. If the command parameters are correct, there is usually no problem. The Tars Node startup service also starts the service by creating a shell execution file tars_start.sh, and saves the startup script in the bin directory of the corresponding service. Start the service manually. An exception occurs after manually starting and stopping the service. It may be because there is a problem with the parameter configuration when starting the service. You can refer to the startup script in the service bin directory. The difference between manually starting and stopping through the TarsFramework management is the service log. Each time the service is started and stopped through the Tars framework, the service information and status are updated in the database.

**Comment by TARS-Answer** [comment]
一般来说不建议通过登录服务器直接进行服务启动与停止，存在一定的安全问题。直接启动或停止服务，命令参数正确的话，通常不会存在问题，Tars Node启动服务也是通过创建shell执行文件tars_start.sh来启动服务的，并且会将启动脚本保存在对应服务的bin目录下，供手动启动服务。手动启停服务后出现异常，可能是因为启动服务时的参数配置存在问题，可以参考服务bin目录下的启动脚本。手动启停于通过TarsFramework管理的区别在于服务日志，每次通过Tars框架启动与停止服务都会在数据库中更新服务的信息与状态。
