### ISSUE TITLE
Why are there a lot of assert in tars production code?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#592]
- This will be disabled when compiling, 

- right? Will the online ones be banned? 

- Which compilation option is prohibited?

**Comment by TARS-Answer** [comment]
It is used for debugging. It should not be encountered normally. If it is encountered, it means there is a bug. If the online version is released, assert will not take effect.

**Comment by TARS-Answer** [comment]
调试用的，正常不应该碰到，碰到就说明有bug。线上的如果用release版本，assert就不会生效。
linux下默认就是release，release就自动禁止了。一般不要禁止，在跑程序时如果中断了，就说明有致命bug。

**Comment by TARS-Question** [comment]
Can I crash it online?

**Comment by TARS-Question** [comment]
那可以线上直接让它crash掉吗？

**Comment by TARS-Answer** [comment]
Assert usually doesn't crash and doesn't work normally. It should be tested and found that it shouldn't exist online. If it does exist online, it can only crash, otherwise the program can't work. If release is used, online assert will not be triggered. However, in this case, the program may be in an unknown state.
For serious internal logic errors, this general debugging stage should be triggered. The reason why assert is convenient for debugging is that you can probably know what the problem is by looking at assert.

**Comment by TARS-Answer** [comment]
assert一般都是不crash也不能正常工作的，这种都应该测试就发现了，线上不应该有，如果线上真的有，就只能crash，不然程序都没法工作了。如果用的是release，线上assert不会触发的，不过真的有碰到这种情况，程序可能就处于未知状态了。
而严重的内部逻辑错误，这种一般debug阶段就应该触发了，之所以有assert，是调试方便，一看assert大概就知道是什么问题了。
