### ISSUE TITLE
One framework and one node are installed locally via docker, and now a spring boot project is started through the web console, and it cannot be started smoothly. 

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#601]
- Screenshot of template file

> ![#601(1)](https://user-images.githubusercontent.com/66677505/85870875-395b0a80-b800-11ea-95b6-a90be7e17752.jpg)

- Web console output

> ![#601(2)](https://user-images.githubusercontent.com/66677505/85870907-437d0900-b800-11ea-8450-2e3d092532aa.png)

- Log of Web

> ![#601(3)](https://user-images.githubusercontent.com/66677505/85870915-4546cc80-b800-11ea-8255-93ebba8b299a.jpg)

- The template selected is a custom template. However, after I log in to the container and start this jar, it can work normally. How should I deal with this problem?

**Comment by TARS-Answer** [comment]
Starting the service through the console is not standardized, and there are many possible reasons for failure, such as incorrect input parameters and template file errors. The template file in Figure 1 is wrong. The values of some fields need to be replaced. Publishing through TarsWeb will automatically complete the replacement process. The high probability of error on the left of Figure 2 is because port 3001 is not opened, TarsWeb opens authentication by default, and you need to jump to port 3001. The latest TarsWeb has merged authentication, no more ports are opened, and can be repaired by upgrading TrsWeb.

**Comment by TARS-Answer** [comment]
通过控制台启动服务并不规范，失败可能原因较多，比如传入参数错误，模板文件错误等。图一中的模板文件是错误的，一些字段的值需要替换，通过TarsWeb发布会自动完成替换这个过程。图二左边错误大概率是因为3001端口没开，TarsWeb默认开启鉴权，需要跳转到3001端口。最新的TarsWeb已经将鉴权合并，不再多开端口，可以通过升级TrsWeb进行修复。
