### ISSUE TITLE
What are the main reasons for ARS to replace fastjson with gson instead of Jackson?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#659]
I think Jackson has similar security problems;

So I want to know it. Internal business will replace fastjson.

**Comment by TARS-Answer** [comment]
Google's JSON library is relatively stable, safe and adaptable. This follow-up will be abstracted into customization.


The biggest core point of choosing gson is that gson has no major problems since it came into being. The logic and neatness of the implementation from the code is also suitable. Of course, tarsjava still can't say which serialization tool to use. It should be used by users themselves. Gson is just a recommendation.

**Comment by TARS-Answer** [comment]
google的json库相对稳定安全，适应性广，这个后续会抽象成自定义吧。

选择gson的最大的核心点还是gson从它产生到现在没有重大的问题。在从代码的实现的逻辑和整洁度也适合。当然tarsjava这里还是不能说，规定用哪种序列化的工具。应该是需要使用者自己使用就好。gson也只是一个推荐哈。
