### ISSUE TITLE
This is an error calling the times between the two tar services.

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#710]
> ![#710(1)](https://user-images.githubusercontent.com/66677505/87856164-c866c880-c94f-11ea-8ad2-da2dfc5f35f5.jpg)

> ![#710(2)](https://user-images.githubusercontent.com/66677505/87856165-c8ff5f00-c94f-11ea-90ba-c5e54e8abf6d.jpg)

**Comment by TARS-Answer** [comment]
As shown in the picture, if @ TCP... Is removed, there will be problems.
<img width="1048" alt="QQ图片20200719113328" src="https://user-images.githubusercontent.com/66677645/87866395-ef56e600-c9b3-11ea-9378-413fdac5c9d5.png">

This is caused by the error of getting configuration file; without the block in the remarks, you can use getcommunicator directly, and you don't need to develop a config deployment environment in the tars. (see the two documents https://tarscloud.github.io/TarsDocs/dev/tarsjava/tars-quick-start.html  and   
https://tarscloud.github.io/TarsDocs/dev/tarsjava/tars-tutorials.html ) these two documents can be developed from the client side and the server side. All the online services are here. You can install the documents step by step.

The example of the official website is a direct new one. It's an old document, which is running locally in a tars environment. The new document has an explanation for this.

**Comment by TARS-Answer** [comment]
如图所示如果把@tcp ... 去掉就会有问题。
<img width="1048" alt="QQ图片20200719113328" src="https://user-images.githubusercontent.com/66677645/87866410-2cbb7380-c9b4-11ea-998a-aa935fab1c12.png">

这里是由于配置文件获取错误导致的；不需要备注中的块，直接getcommunicator就可以使用，不需要制定config在tars部署环境。(见两个文档  https://tarscloud.github.io/TarsDocs/dev/tarsjava/tars-quick-start.html  和
https://tarscloud.github.io/TarsDocs/dev/tarsjava/tars-tutorials.html )这两个文档可以从客户端·服务端开发，服务上线全部都在这了，安文档的一步一步处理即可。
官网的例子是直接new的一个，那个是老的文档，是脱离tars环境下本地跑的，新的文档上面对这块有说明。
