### ISSUE TITLE
A question: I have a service A, online environment. I have deployment in multiple regions with different configurations. How can I do this?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#741]
For example, Shenzhen and Shanghai have different DB configurations. How can I identify which configuration I use?

**Comment by TARS-Answer** [comment]
In your private template, specify the current - DENV = AreaA and - DENV = areab, which is OK. Because at startup, you can specify the configuration module for the current service.

Our approach is to configure independent configuration information in the private template, so that different configuration files can be loaded. (see note Figure)

CommunicatorFactory.getInstance ().getCommunicator().getCommunicatorConfig().getSetDivision()

If your configuration follows the environment, you can also partition your configuration information during setdivisioin. After obtaining the current setdivisioin, you can read your configuration. Through this API, you can get all the information of the current setdivisioin that has been configured on the platform.
![QQ图片20200722235624](https://user-images.githubusercontent.com/66677645/88199261-30cae800-cc77-11ea-9789-04c563890a32.jpg)

**Comment by TARS-Answer** [comment]
在你的私有模板里面指定当前的-DENV=AREAA  和-DENV=AREAB，这样就可以了。因为在启动的时候，可以针对当前的服务指定配置模块的。
我们的做法是在私有模板这里配置独立的这一些配置的信息，这样加载就可以不同的配置文件了。(见备注图）
CommunicatorFactory.getInstance().getCommunicator().getCommunicatorConfig().getSetDivision() 
若是你的配置是跟着环境走，也可以在setDivisoin的时候，划分好你的配置信息，获取到当前的setDivisoin后，再去读取你的配置，这也是可以的。通过这个API就可以获取当前的已经配置在平台上面的setDivisoin的所有的信息了
![QQ图片20200722235624](https://user-images.githubusercontent.com/66677645/88199326-47713f00-cc77-11ea-98e8-9705666214d7.jpg)

**Comment by TARS-Question** [comment]
This is to set the configuration of existing machine nodes in batch, and then when the capacity is expanded, will the configuration of this private template be automatically carried?

**Comment by TARS-Question** [comment]
这个是要批量设置已有机器节点的配置，然后扩容的时候，自动会把这个私有模板的配置携带上的吗？

**Comment by TARS-Answer** [comment]
When expanding, when the source IP node is specified, then copy is the private template of the IP node. (see note Figure）
![2](https://user-images.githubusercontent.com/66677645/88199443-738cc000-cc77-11ea-8e6f-fa28a95db7c9.jpg)

**Comment by TARS-Answer** [comment]
扩容的时候，会指定源ip的节点的时候，那么copy的时候，就是这个ip节点的私有模板。(见备注图)
![2](https://user-images.githubusercontent.com/66677645/88199497-843d3600-cc77-11ea-99aa-9a1e794750a4.jpg)

**Comment by TARS-Question** [comment]
Copy the configuration of the template here to the private template, right? And then change the different places here, OK?

> ![#741(3)](https://user-images.githubusercontent.com/66677505/88199508-87d0bd00-cc77-11ea-8a0c-4454367f0b1f.jpg)

Is it possible to build multiple templates (Shenzhen, Shanghai) without using private templates, and then select different templates for different nodes.

**Comment by TARS-Answer** [comment]
Yes, node configuration is also OK (see note Figure). However, we usually use private templates and get setdivisioin to handle it. In this way, we don't need to pay attention to the configuration of this part, and avoid some risks of online when publishing.
![4](https://user-images.githubusercontent.com/66677645/88199575-9e771400-cc77-11ea-9a9a-552f0c5d2b39.jpg)

**Comment by TARS-Question** [comment]
是把这里模板的配置，全量拷贝到私有模板这里是吗？然后再这里修改下不同的地方，这样吗？

> ![#741(3)](https://user-images.githubusercontent.com/66677505/88199579-a0d96e00-cc77-11ea-91f3-52942f4c2f93.jpg)

是不是也可以不用私有模板，我建多个模板(深圳，上海)，然后不同的节点，选择不同的模板。

**Comment by TARS-Answer** [comment]
Yes, node configuration is also OK (see note Figure). However, we usually use private templates and get setdivisioin to handle it. In this way, we don't need to pay attention to the configuration of this part, and avoid some risks of online when publishing.
![4](https://user-images.githubusercontent.com/66677645/88199680-ba7ab580-cc77-11ea-8372-478ae7b3fb41.jpg)

**Comment by TARS-Answer** [comment]
是的，节点配置也是可以的(见备注图四)。不过我们这里一般用的是私有模板和获取setDivisoin来处理，这样发布就不用关心这一部分的配置了，在发布的时候，避免一些上线的风险。
![4](https://user-images.githubusercontent.com/66677645/88199768-d67e5700-cc77-11ea-8327-91ca45d1c69c.jpg)
