### ISSUE TITLE
Under the same TARS cluster, are TarLog and TasPatch the same as tarsAdminRegisrty, and there can only be one instance?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#747]

**Comment by TARS-Answer** [comment]
Yes, tarspatch needs to be with tarsweb. Because of the uploaded release package, tarspatch needs to access it. If you use a shared disk, you can deploy multiple tarspatch. But tarslog is generally one set, you can use multiple sets, use templates to assign different business services, and report logs to different tarslogs. It is equivalent to tarslog is the log server, which receives the logs of each tars service.

**Comment by TARS-Answer** [comment]
是的，tarspatch需要和tarsweb在一起。因为上传的发布包, tarspatch需要访问到。如果使用一个共享盘，就可以部署多台tarspatch了。但tarslog, 一般就一台, 你可以多台, 用模板分配不同的业务服务, 上报日志到不同的tarslog。相当于tarslog是log服务端，接收各tars服务日志的。
