### ISSUE TITLE
  How does tarsgo implement HTTPS?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#786]

**Comment by TARS-Answer** [comment]
TarsGo implements TarsHttpMux based on http natively encapsulated by Go. It is very simple to use, but it does not provide HTTPS-related analysis. Since HTTP is not a tars protocol and has little to do with the tars framework, you can directly use the http package natively encapsulated by Go to implement https.

**Comment by TARS-Answer** [comment]
TarsGo中基于Go原生封装的http，实现了TarsHttpMux，使用上非常简单，但是没有提供HTTPS相关的解析。由于HTTP不是tars协议，与tars框架关系不大，可以自行直接使用Go原生封装的http包实现https。
