### ISSUE TITLE
Running Linux_ install.sh Error installing tars framework, log output MySQL access failed? Is it a bug? 

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#793]
Maria DB 10.4.13 was used.

**Comment by TARS-Answer** [comment]
The installation script will automatically create a TarsAdmin database user for subsequent service use. The installation script executes the corresponding creation commands by detecting the user mysql version, because different versions of mysql are different. But mariaDB is special, so the creation of TarsAdmin user may not be executed successfully.

**Comment by TARS-Answer** [comment]
安装脚本运行过程会自动创建TarsAdmin数据库用户，用于后续服务的使用。安装脚本通过检测用户mysql版本来执行相应的创建命令，因为不同版本mysql有所差别。但是mariaDB较为特殊，因此可能没有成功执行TarsAdmin用户的创建。
